apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opa-example-app
  namespace: opa-example-app
spec:
  host: opa.apps.cluster-8713.8713.example.opentlc.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: opa-example-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opa-example-app-short-host
  namespace: opa-example-app
spec:
  host: opa.apps.cluster-8713.8713.example.opentlc.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: opa-example-app
